const LOGIN = 'LOGIN'
const LOGOUT = 'LOGOUT'
const REGISTER = 'REGISTER'
const SET_ALERT = 'SET_ALERT'
const SEND_MESSAGE = 'SEND_MESSAGE'

export { LOGIN, LOGOUT, REGISTER, SET_ALERT, SEND_MESSAGE }